API_HOST_URL: 'https://learn-stage.tndy.academy/' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
PLATFORM_NAME: 'SDAIA MVP'
PLATFORM_DESTINATION_NAME: 'example.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
API_URL_VERSION:
  BLOCKS: "v2"
  REGISTRATION: "v2"
  ENROLLMENTS: "v2"
